version: '3.4'
services:
  mysql:
    container_name: kakaologin-db
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile_DB
    volumes:
      - ./Database/data/db/conf.d:/etc/mysql/conf.d
      - ./Database/data/db/data:/var/lib/mysql
    ports:
      - 3348:3306
    restart: always
    environment:
      - MYSQL_USER=kakao
      - MYSQL_ROOT_PASSWORD=Zmffkdnem12
      - MYSQL_PASSWORD=Zmffkdnem12
      - MYSQL_DATABASE=kakao
    mem_limit: 4096M

  backend:
    container_name: kakaologin-backend
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile_Backend_With_Proxy
      args:
        PROXY_ADDR: "http://192.168.0.73:8888"
    depends_on: ["mysql"]
    ports:
      - 8083:8083
    restart: always