FROM maven:3.9.6-eclipse-temurin-17

COPY ../Backend/. ./

EXPOSE 8080

RUN mkdir -p /app
RUN apt update -y
RUN chmod +x ./gradlew
RUN ./gradlew bootjar
RUN cp ./build/libs/kakao-api-server-0.0.1-SNAPSHOT.jar /app/app.jar

ENTRYPOINT ["java", "-jar", "/app/app.jar"]