FROM node

COPY ../.env /.env
COPY ../Backend/. ./

EXPOSE 8080
WORKDIR /app

RUN apt update -y
RUN chmod +x ./gradlew
RUN ./gradlew bootjar
RUN cp ./build/libs/kakao-api-server-0.0.1-SNAPSHOT.jar /app/app.jar

ENTRYPOINT ["java", "-jar", "/app/app.jar"]